#!/usr/bin/env python3
"""Draw the GZ mark from the bundled Fira Sans, as paths.

The other artwork here sets <text> and pins it with textLength, which is
what you do when the mark has to survive a machine that has none of our
fonts. It survives; it is not identical. This turns the same letters into
outlines once, here, so every rendering of the badge is the same shape —
and so a PNG made on this laptop matches the SVG a browser draws.

Needs fonttools (with brotli, for the woff2) and rsvg-convert. Neither is
a build dependency: the output is committed, and this is how it was made.

    python3 packaging/branding/build.py
"""

import pathlib
import subprocess

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
FONT = ROOT / "internal/webui/fonts/fira-sans-700.woff2"

TEXT = "GZ"
TRACKING = -0.03  # em; .cpr-brand-mark's letter-spacing
BOX = 300
RADIUS = 64  # 9/42 of the box, the badge's own proportion
INK_WIDTH = 0.65  # of the box, which is what 15px type in a 42px badge is

ORANGE = "#E35E30"  # the badge ground in the interface
CPANEL_ORANGE = "#CF470C"  # cPanel's own, for ink on a light surface
WHITE = "#FFFFFF"

PNG_SIZES = (16, 32, 48, 64, 128, 256, 512)


def run(text):
    """Glyph outlines for `text`, positioned on one baseline."""
    font = TTFont(FONT)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    metrics = font["hmtx"]

    placed, pen_x = [], 0.0
    for char in text:
        name = cmap[ord(char)]
        placed.append((name, pen_x))
        pen_x += metrics[name][0] + TRACKING * upm

    left, bottom, right, top = 1e9, 1e9, -1e9, -1e9
    for name, offset in placed:
        bounds = BoundsPen(glyphs)
        glyphs[name].draw(bounds)
        if bounds.bounds is None:
            continue
        x0, y0, x1, y1 = bounds.bounds
        left, right = min(left, x0 + offset), max(right, x1 + offset)
        bottom, top = min(bottom, y0), max(top, y1)
    return glyphs, placed, (left, bottom, right, top)


def path(box=BOX, ink=INK_WIDTH):
    """One `d` attribute: the run scaled to `ink` of `box` and centred."""
    glyphs, placed, (left, bottom, right, top) = run(TEXT)
    scale = ink * box / (right - left)
    origin_x = (box - (right - left) * scale) / 2 - left * scale
    # SVG's y grows downward, so the glyphs are flipped about the baseline.
    origin_y = (box + (top - bottom) * scale) / 2 + bottom * scale

    commands = []
    for name, offset in placed:
        pen = SVGPathPen(glyphs, ntos=lambda value: f"{value:.2f}")
        glyphs[name].draw(TransformPen(pen, Transform(
            scale, 0, 0, -scale, origin_x + offset * scale, origin_y)))
        if pen.getCommands():
            commands.append(pen.getCommands())
    return " ".join(commands)


HEAD = ('<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by packaging/branding/build.py. The letters are\n'
        '     outlines of Fira Sans Bold, so nothing here needs a font. -->\n')


def badge():
    return HEAD + (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BOX} {BOX}"'
        f' width="{BOX}" height="{BOX}" role="img" aria-label="GZ">\n'
        f'  <rect width="{BOX}" height="{BOX}" rx="{RADIUS}" fill="{ORANGE}"/>\n'
        f'  <path fill="{WHITE}" d="{path()}"/>\n'
        '</svg>\n')


def mark(colour, name):
    """The letters alone, no ground, trimmed to the ink."""
    glyphs, placed, (left, bottom, right, top) = run(TEXT)
    width = BOX * INK_WIDTH
    height = width * (top - bottom) / (right - left)
    scale = width / (right - left)
    commands = []
    for glyph, offset in placed:
        pen = SVGPathPen(glyphs, ntos=lambda value: f"{value:.2f}")
        glyphs[glyph].draw(TransformPen(pen, Transform(
            scale, 0, 0, -scale, -left * scale + offset * scale, top * scale)))
        if pen.getCommands():
            commands.append(pen.getCommands())
    return HEAD + (
        f'<svg xmlns="http://www.w3.org/2000/svg"'
        f' viewBox="0 0 {width:.0f} {height:.0f}"'
        f' width="{width:.0f}" height="{height:.0f}"'
        f' role="img" aria-label="GZ">\n'
        f'  <path fill="{colour}" d="{" ".join(commands)}"/>\n'
        '</svg>\n')


def main():
    (HERE / "badge.svg").write_text(badge())
    (HERE / "mark.svg").write_text(mark(CPANEL_ORANGE, "mark"))
    (HERE / "mark-white.svg").write_text(mark(WHITE, "mark-white"))

    png = HERE / "png"
    png.mkdir(exist_ok=True)
    for size in PNG_SIZES:
        subprocess.run([
            "rsvg-convert", "-w", str(size), "-h", str(size),
            str(HERE / "badge.svg"),
            "-o", str(png / f"badge-{size}.png"),
        ], check=True)
    for size in (256, 512):
        subprocess.run([
            "rsvg-convert", "-w", str(size),
            str(HERE / "mark.svg"),
            "-o", str(png / f"mark-{size}.png"),
        ], check=True)
    print("wrote", HERE / "badge.svg", "and", len(PNG_SIZES) + 2, "PNGs")


if __name__ == "__main__":
    main()
